/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DSM_H_RPCGEN
#define _DSM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct initializationNode {
	char ips[500];
	int nodeNum;
};
typedef struct initializationNode initializationNode;

struct localNode {
	char state;
	char fileName[20];
	char IP[20];
	int offset;
	int outstandingReplies;
	int highestSeqNum;
	int requestStatus;
	char operation;
	int lockId;
};
typedef struct localNode localNode;

struct ReqNode {
	char IP[20];
	char data[1000];
	char fileName[20];
	char state;
	int seqNum;
	int nodeNum;
	bool_t bRequestingCS;
	int lockId;
	int resultCode;
};
typedef struct ReqNode ReqNode;

#define InitializeServer_PROG 0x23451111
#define InitializeServer_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define InitializeServer 1
extern  int * initializeserver_1(initializationNode *, CLIENT *);
extern  int * initializeserver_1_svc(initializationNode *, struct svc_req *);
extern int initializeserver_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define InitializeServer 1
extern  int * initializeserver_1();
extern  int * initializeserver_1_svc();
extern int initializeserver_prog_1_freeresult ();
#endif /* K&R C */

#define GetMemPtr_PROG 0x23451112
#define GetMemPtr_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetMemPtr 1
extern  char * getmemptr_1(localNode *, CLIENT *);
extern  char * getmemptr_1_svc(localNode *, struct svc_req *);
extern int getmemptr_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetMemPtr 1
extern  char * getmemptr_1();
extern  char * getmemptr_1_svc();
extern int getmemptr_prog_1_freeresult ();
#endif /* K&R C */

#define GetLocalData_PROG 0x23451113
#define GetLocalData_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetLocalData 1
extern  localNode * getlocaldata_1(localNode *, CLIENT *);
extern  localNode * getlocaldata_1_svc(localNode *, struct svc_req *);
extern int getlocaldata_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetLocalData 1
extern  localNode * getlocaldata_1();
extern  localNode * getlocaldata_1_svc();
extern int getlocaldata_prog_1_freeresult ();
#endif /* K&R C */

#define RecRep_PROG 0x23451114
#define RecRep_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RecRep 1
extern  ReqNode * recrep_1(ReqNode *, CLIENT *);
extern  ReqNode * recrep_1_svc(ReqNode *, struct svc_req *);
extern int recrep_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RecRep 1
extern  ReqNode * recrep_1();
extern  ReqNode * recrep_1_svc();
extern int recrep_prog_1_freeresult ();
#endif /* K&R C */

#define GetAdd_PROG 0x23451115
#define GetAdd_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetAdd 1
extern  ReqNode * getadd_1(ReqNode *, CLIENT *);
extern  ReqNode * getadd_1_svc(ReqNode *, struct svc_req *);
extern int getadd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetAdd 1
extern  ReqNode * getadd_1();
extern  ReqNode * getadd_1_svc();
extern int getadd_prog_1_freeresult ();
#endif /* K&R C */

#define SendAdd_PROG 0x23451116
#define SendAdd_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SendAdd 1
extern  ReqNode * sendadd_1(ReqNode *, CLIENT *);
extern  ReqNode * sendadd_1_svc(ReqNode *, struct svc_req *);
extern int sendadd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SendAdd 1
extern  ReqNode * sendadd_1();
extern  ReqNode * sendadd_1_svc();
extern int sendadd_prog_1_freeresult ();
#endif /* K&R C */

#define GetUpdates_PROG 0x23451117
#define GetUpdates_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetUpdates 1
extern  ReqNode * getupdates_1(ReqNode *, CLIENT *);
extern  ReqNode * getupdates_1_svc(ReqNode *, struct svc_req *);
extern int getupdates_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetUpdates 1
extern  ReqNode * getupdates_1();
extern  ReqNode * getupdates_1_svc();
extern int getupdates_prog_1_freeresult ();
#endif /* K&R C */

#define SendUpdates_PROG 0x23451118
#define SendUpdates_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SendUpdates 1
extern  ReqNode * sendupdates_1(ReqNode *, CLIENT *);
extern  ReqNode * sendupdates_1_svc(ReqNode *, struct svc_req *);
extern int sendupdates_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SendUpdates 1
extern  ReqNode * sendupdates_1();
extern  ReqNode * sendupdates_1_svc();
extern int sendupdates_prog_1_freeresult ();
#endif /* K&R C */

#define ReqCS_PROG 0x23451119
#define ReqCS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ReqCS 1
extern  localNode * reqcs_1(localNode *, CLIENT *);
extern  localNode * reqcs_1_svc(localNode *, struct svc_req *);
extern int reqcs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ReqCS 1
extern  localNode * reqcs_1();
extern  localNode * reqcs_1_svc();
extern int reqcs_prog_1_freeresult ();
#endif /* K&R C */

#define ReqCS1_PROG 0x23451120
#define ReqCS1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ReqCS1 1
extern  localNode * reqcs1_1(localNode *, CLIENT *);
extern  localNode * reqcs1_1_svc(localNode *, struct svc_req *);
extern int reqcs1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ReqCS1 1
extern  localNode * reqcs1_1();
extern  localNode * reqcs1_1_svc();
extern int reqcs1_prog_1_freeresult ();
#endif /* K&R C */

#define RecReq_PROG 0x23451121
#define RecReq_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RecReq 1
extern  ReqNode * recreq_1(ReqNode *, CLIENT *);
extern  ReqNode * recreq_1_svc(ReqNode *, struct svc_req *);
extern int recreq_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RecReq 1
extern  ReqNode * recreq_1();
extern  ReqNode * recreq_1_svc();
extern int recreq_prog_1_freeresult ();
#endif /* K&R C */

#define Dummy1_PROG 0x23451122
#define Dummy1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Dummy1 1
extern  localNode * dummy1_1(localNode *, CLIENT *);
extern  localNode * dummy1_1_svc(localNode *, struct svc_req *);
extern int dummy1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Dummy1 1
extern  localNode * dummy1_1();
extern  localNode * dummy1_1_svc();
extern int dummy1_prog_1_freeresult ();
#endif /* K&R C */

#define Dummy2_PROG 0x23451123
#define Dummy2_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Dummy2 1
extern  char * dummy2_1(ReqNode *, CLIENT *);
extern  char * dummy2_1_svc(ReqNode *, struct svc_req *);
extern int dummy2_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Dummy2 1
extern  char * dummy2_1();
extern  char * dummy2_1_svc();
extern int dummy2_prog_1_freeresult ();
#endif /* K&R C */

#define Dummy3_PROG 0x23451124
#define Dummy3_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Dummy3 1
extern  ReqNode * dummy3_1(ReqNode *, CLIENT *);
extern  ReqNode * dummy3_1_svc(ReqNode *, struct svc_req *);
extern int dummy3_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Dummy3 1
extern  ReqNode * dummy3_1();
extern  ReqNode * dummy3_1_svc();
extern int dummy3_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_initializationNode (XDR *, initializationNode*);
extern  bool_t xdr_localNode (XDR *, localNode*);
extern  bool_t xdr_ReqNode (XDR *, ReqNode*);

#else /* K&R C */
extern bool_t xdr_initializationNode ();
extern bool_t xdr_localNode ();
extern bool_t xdr_ReqNode ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DSM_H_RPCGEN */
