/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DSM.h"

#include <stdio.h>
#include <stdlib.h>

#include <string.h>

#include <sys/ipc.h>
#include <sys/types.h>
#include <sys/shm.h>
#include <signal.h>
#include<sys/mman.h>

#include <pthread.h>


#define channelCount 2
#define MAXREQUESTS 10
#define MAXRES 5
typedef enum { false, true } bool;

char nullStr[1] = "\0";

localNode myInfo[15];

char *toWrite;
char toWrite1[1000];
int WriteSize = 1000;

struct Node{
	char IP[20];
};


char *shm;

void handler(int sign)
{
    printf("handler mein hai %d\n",sign);
    mprotect((void *)shm,SHMSIZE,PROT_READ | PROT_WRITE);
    memcpy(shm,"maa chuda",9);
    printf("%s\n",shm);
    printf("Access has been changed\n");
}

void removeSubstring(char *str, char *toRemove)
{
	if (NULL == (str = strstr(str, toRemove)))
	{
		// no match.
		//printf("No match in %s\n", str);
		return;
	}

	// str points to toRemove in str now.
	const size_t remLen = strlen(toRemove);
	char *copyEnd;
	char *copyFrom = str + remLen;
	while (NULL != (copyEnd = strstr(copyFrom, toRemove)))
	{
		//printf("match at %3ld in %s\n", copyEnd - str, str);
		memmove(str, copyFrom, copyEnd - copyFrom);
		str += copyEnd - copyFrom;
		copyFrom = copyEnd + remLen;
	}
	memmove(str, copyFrom, 1 + strlen(copyFrom));
}

void
initializeserver_prog_1(char nodeNum[])
{
	char host[20];
	 
	CLIENT *clnt;
	int  *result_1;
	initializationNode  initializeserver_1_arg;
	initializeserver_1_arg.nodeNum = atoi(nodeNum);	
	printf("%s\n",nodeNum);

	strcat(nodeNum,".txt");
	printf("%s\n",nodeNum);
	
	FILE *fileAddr = fopen(nodeNum, "r");
	char buffer[500]; 
	fgets(buffer, 100, fileAddr);
	removeSubstring(buffer, "\n");
	char toPlay[100];
	char *token;
	char ips[500];
	strcpy(ips,buffer);
	//printf("buffer%s\n",buffer);
	int count = 0, j = 0, i = 0, k = 0;
	struct Node nodes[channelCount+1];

	while (j < strlen(ips))
	{
		if (ips[j] == ',')
		{
			nodes[count].IP[i] = '\0';
			i = 0;
			j++;

			//printf("node of count %s\n",nodes[count].IP);
			count++;
			
		}
		else
		{
			nodes[count].IP[i] = ips[j];
			j++;
			i++;
		}
	}
	nodes[count].IP[i] = '\0';
 
	strcpy(host,nodes[channelCount].IP);

	strcpy(initializeserver_1_arg.ips,buffer);
	
	printf("%sPS.........................PS.........................\n",initializeserver_1_arg.ips);
	printf("%smy host address\n",host);
	clnt = clnt_create (host, InitializeServer_PROG, InitializeServer_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}  
	result_1 = initializeserver_1(&initializeserver_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} 
	clnt_destroy (clnt); 



	count =0;
	while (fgets(buffer, 100, fileAddr))
	{
		if(strcmp(buffer,"END") == 0)
		{
			break;
		}
		else{
		removeSubstring(buffer, "\n");
	 
		CLIENT *clnt;
		localNode  *result_1; 
		
		char toPlay[100];
		strcpy(toPlay,buffer);
		char *token;
		 sleep(2);  
		for (i = 0, token = strtok(toPlay, ","); token; token = strtok(NULL, ","), i++)
		{
			if(i==0)
			{
				if(strcmp("R",token) == 0)
				{
					myInfo[count].operation = 'S';
					myInfo[count].state = 'S';
				}
				else{
					myInfo[count].operation = 'M';
					myInfo[count].state = 'M';
				}
			}
			else if(i==1)
			{
				strcpy(myInfo[count].fileName,token);
			}
			else if(i==3)
			{
				myInfo[count].offset = atoi(token);
			}
			else if(i==4)
			{
				strcpy(toWrite1,token);
			}
		}
		strcpy(myInfo[count].IP,host);
		myInfo[count].outstandingReplies = channelCount;
		myInfo[count].highestSeqNum = 0;
		myInfo[count].lockId = count; 
		myInfo[count].outstandingReplies = channelCount;
		myInfo[count].requestStatus = -1;

		clnt = clnt_create (host, ReqCS_PROG, ReqCS_VERS, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
		result_1 = reqcs_1(&myInfo[count], clnt);

		if (result_1 == (localNode *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		clnt_destroy (clnt);

		while(myInfo[count].outstandingReplies > 0)
		{
			sleep(1); 
			CLIENT *clnt;
			localNode  *result_1;
			localNode  getlocaldata_1_arg;
			clnt = clnt_create (host, GetLocalData_PROG, GetLocalData_VERS, "tcp");
			if (clnt == NULL) {
			clnt_pcreateerror (host);
				exit (1);
			} 
			result_1 = getlocaldata_1(&(myInfo[count]), clnt);
			if (result_1 == (localNode *) NULL) {
				clnt_perror (clnt, "call failed");
			} 
			myInfo[count].outstandingReplies = result_1->outstandingReplies;
			myInfo[count].highestSeqNum = result_1->highestSeqNum;
  
			clnt_destroy (clnt); 
		}
		printf("Done for operation %c for file %s\n",myInfo[count].operation,myInfo[count].fileName);
		}
		count++;
	}
 
	fclose(fileAddr);
	

}


void
getmemptr_prog_1(char *host)
{
	CLIENT *clnt;
	char  *result_1;
	localNode  getmemptr_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GetMemPtr_PROG, GetMemPtr_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getmemptr_1(&getmemptr_1_arg, clnt);
	if (result_1 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
getlocaldata_prog_1(char *host)
{
	CLIENT *clnt;
	localNode  *result_1;
	localNode  getlocaldata_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GetLocalData_PROG, GetLocalData_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getlocaldata_1(&getlocaldata_1_arg, clnt);
	if (result_1 == (localNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
recrep_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  recrep_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RecRep_PROG, RecRep_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = recrep_1(&recrep_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
getadd_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  getadd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GetAdd_PROG, GetAdd_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getadd_1(&getadd_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sendadd_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  sendadd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SendAdd_PROG, SendAdd_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sendadd_1(&sendadd_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
getupdates_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  getupdates_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GetUpdates_PROG, GetUpdates_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getupdates_1(&getupdates_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sendupdates_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  sendupdates_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SendUpdates_PROG, SendUpdates_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sendupdates_1(&sendupdates_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
reqcs_prog_1(char *host)
{
	CLIENT *clnt;
	localNode  *result_1;
	localNode  reqcs_1_arg;
	clnt = clnt_create (host, ReqCS_PROG, ReqCS_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	result_1 = reqcs_1(&reqcs_1_arg, clnt);
	if (result_1 == (localNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt); 
}


void
reqcs1_prog_1(char *host)
{
	CLIENT *clnt;
	localNode  *result_1;
	localNode  reqcs1_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ReqCS1_PROG, ReqCS1_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = reqcs1_1(&reqcs1_1_arg, clnt);
	if (result_1 == (localNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
recreq_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  recreq_1_arg;

	clnt = clnt_create (host, RecReq_PROG, RecReq_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = recreq_1(&recreq_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);
}


void
dummy1_prog_1(char *host)
{
	CLIENT *clnt;
	localNode  *result_1;
	localNode  dummy1_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Dummy1_PROG, Dummy1_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = dummy1_1(&dummy1_1_arg, clnt);
	if (result_1 == (localNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
dummy2_prog_1(char *host)
{
	CLIENT *clnt;
	char  *result_1;
	ReqNode  dummy2_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Dummy2_PROG, Dummy2_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = dummy2_1(&dummy2_1_arg, clnt);
	if (result_1 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
dummy3_prog_1(char *host)
{
	CLIENT *clnt;
	ReqNode  *result_1;
	ReqNode  dummy3_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Dummy3_PROG, Dummy3_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = dummy3_1(&dummy3_1_arg, clnt);
	if (result_1 == (ReqNode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{	
	char *host;
	signal(SIGSEGV,handler);
	int shmid;
	key_t key;
	char *s;



	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);

		exit (1);
	}
	host = argv[1]; 
	initializeserver_prog_1 (host);
 
exit (0);
}
