/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "DSM.h"

bool_t
xdr_initializationNode (XDR *xdrs, initializationNode *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ips, 500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nodeNum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_localNode (XDR *xdrs, localNode *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_char (xdrs, &objp->state))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->outstandingReplies))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->highestSeqNum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->requestStatus))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->offset);
		IXDR_PUT_LONG(buf, objp->outstandingReplies);
		IXDR_PUT_LONG(buf, objp->highestSeqNum);
		IXDR_PUT_LONG(buf, objp->requestStatus);
		}
		 if (!xdr_char (xdrs, &objp->operation))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->lockId))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_char (xdrs, &objp->state))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->outstandingReplies))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->highestSeqNum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->requestStatus))
				 return FALSE;

		} else {
		objp->offset = IXDR_GET_LONG(buf);
		objp->outstandingReplies = IXDR_GET_LONG(buf);
		objp->highestSeqNum = IXDR_GET_LONG(buf);
		objp->requestStatus = IXDR_GET_LONG(buf);
		}
		 if (!xdr_char (xdrs, &objp->operation))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->lockId))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_char (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->outstandingReplies))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->highestSeqNum))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->requestStatus))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operation))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lockId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ReqNode (XDR *xdrs, ReqNode *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->data, 1000,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->state))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->seqNum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nodeNum))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->bRequestingCS))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->lockId))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resultCode))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->seqNum);
			IXDR_PUT_LONG(buf, objp->nodeNum);
			IXDR_PUT_BOOL(buf, objp->bRequestingCS);
			IXDR_PUT_LONG(buf, objp->lockId);
			IXDR_PUT_LONG(buf, objp->resultCode);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->data, 1000,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->state))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->seqNum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nodeNum))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->bRequestingCS))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->lockId))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resultCode))
				 return FALSE;
		} else {
			objp->seqNum = IXDR_GET_LONG(buf);
			objp->nodeNum = IXDR_GET_LONG(buf);
			objp->bRequestingCS = IXDR_GET_BOOL(buf);
			objp->lockId = IXDR_GET_LONG(buf);
			objp->resultCode = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->IP, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 1000,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seqNum))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nodeNum))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->bRequestingCS))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lockId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->resultCode))
		 return FALSE;
	return TRUE;
}
