/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "DSM.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
initializeserver_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		initializationNode initializeserver_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case InitializeServer:
		_xdr_argument = (xdrproc_t) xdr_initializationNode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) initializeserver_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
getmemptr_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		localNode getmemptr_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GetMemPtr:
		_xdr_argument = (xdrproc_t) xdr_localNode;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (char *(*)(char *, struct svc_req *)) getmemptr_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
getlocaldata_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		localNode getlocaldata_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GetLocalData:
		_xdr_argument = (xdrproc_t) xdr_localNode;
		_xdr_result = (xdrproc_t) xdr_localNode;
		local = (char *(*)(char *, struct svc_req *)) getlocaldata_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
recrep_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode recrep_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RecRep:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) recrep_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
getadd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode getadd_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GetAdd:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) getadd_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
sendadd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode sendadd_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SendAdd:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) sendadd_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
getupdates_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode getupdates_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GetUpdates:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) getupdates_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
sendupdates_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode sendupdates_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SendUpdates:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) sendupdates_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
reqcs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		localNode reqcs_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ReqCS:
		_xdr_argument = (xdrproc_t) xdr_localNode;
		_xdr_result = (xdrproc_t) xdr_localNode;
		local = (char *(*)(char *, struct svc_req *)) reqcs_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
reqcs1_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		localNode reqcs1_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ReqCS1:
		_xdr_argument = (xdrproc_t) xdr_localNode;
		_xdr_result = (xdrproc_t) xdr_localNode;
		local = (char *(*)(char *, struct svc_req *)) reqcs1_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
recreq_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode recreq_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RecReq:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) recreq_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
dummy1_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		localNode dummy1_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Dummy1:
		_xdr_argument = (xdrproc_t) xdr_localNode;
		_xdr_result = (xdrproc_t) xdr_localNode;
		local = (char *(*)(char *, struct svc_req *)) dummy1_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
dummy2_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode dummy2_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Dummy2:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (char *(*)(char *, struct svc_req *)) dummy2_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
dummy3_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ReqNode dummy3_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Dummy3:
		_xdr_argument = (xdrproc_t) xdr_ReqNode;
		_xdr_result = (xdrproc_t) xdr_ReqNode;
		local = (char *(*)(char *, struct svc_req *)) dummy3_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (InitializeServer_PROG, InitializeServer_VERS);
	pmap_unset (GetMemPtr_PROG, GetMemPtr_VERS);
	pmap_unset (GetLocalData_PROG, GetLocalData_VERS);
	pmap_unset (RecRep_PROG, RecRep_VERS);
	pmap_unset (GetAdd_PROG, GetAdd_VERS);
	pmap_unset (SendAdd_PROG, SendAdd_VERS);
	pmap_unset (GetUpdates_PROG, GetUpdates_VERS);
	pmap_unset (SendUpdates_PROG, SendUpdates_VERS);
	pmap_unset (ReqCS_PROG, ReqCS_VERS);
	pmap_unset (ReqCS1_PROG, ReqCS1_VERS);
	pmap_unset (RecReq_PROG, RecReq_VERS);
	pmap_unset (Dummy1_PROG, Dummy1_VERS);
	pmap_unset (Dummy2_PROG, Dummy2_VERS);
	pmap_unset (Dummy3_PROG, Dummy3_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, InitializeServer_PROG, InitializeServer_VERS, initializeserver_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (InitializeServer_PROG, InitializeServer_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GetMemPtr_PROG, GetMemPtr_VERS, getmemptr_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GetMemPtr_PROG, GetMemPtr_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GetLocalData_PROG, GetLocalData_VERS, getlocaldata_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GetLocalData_PROG, GetLocalData_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, RecRep_PROG, RecRep_VERS, recrep_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RecRep_PROG, RecRep_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GetAdd_PROG, GetAdd_VERS, getadd_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GetAdd_PROG, GetAdd_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SendAdd_PROG, SendAdd_VERS, sendadd_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SendAdd_PROG, SendAdd_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GetUpdates_PROG, GetUpdates_VERS, getupdates_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GetUpdates_PROG, GetUpdates_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SendUpdates_PROG, SendUpdates_VERS, sendupdates_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SendUpdates_PROG, SendUpdates_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, ReqCS_PROG, ReqCS_VERS, reqcs_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ReqCS_PROG, ReqCS_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, ReqCS1_PROG, ReqCS1_VERS, reqcs1_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ReqCS1_PROG, ReqCS1_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, RecReq_PROG, RecReq_VERS, recreq_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RecReq_PROG, RecReq_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy1_PROG, Dummy1_VERS, dummy1_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (Dummy1_PROG, Dummy1_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy2_PROG, Dummy2_VERS, dummy2_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (Dummy2_PROG, Dummy2_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy3_PROG, Dummy3_VERS, dummy3_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (Dummy3_PROG, Dummy3_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, InitializeServer_PROG, InitializeServer_VERS, initializeserver_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (InitializeServer_PROG, InitializeServer_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GetMemPtr_PROG, GetMemPtr_VERS, getmemptr_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GetMemPtr_PROG, GetMemPtr_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GetLocalData_PROG, GetLocalData_VERS, getlocaldata_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GetLocalData_PROG, GetLocalData_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RecRep_PROG, RecRep_VERS, recrep_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RecRep_PROG, RecRep_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GetAdd_PROG, GetAdd_VERS, getadd_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GetAdd_PROG, GetAdd_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SendAdd_PROG, SendAdd_VERS, sendadd_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SendAdd_PROG, SendAdd_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GetUpdates_PROG, GetUpdates_VERS, getupdates_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GetUpdates_PROG, GetUpdates_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SendUpdates_PROG, SendUpdates_VERS, sendupdates_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SendUpdates_PROG, SendUpdates_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, ReqCS_PROG, ReqCS_VERS, reqcs_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ReqCS_PROG, ReqCS_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, ReqCS1_PROG, ReqCS1_VERS, reqcs1_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ReqCS1_PROG, ReqCS1_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RecReq_PROG, RecReq_VERS, recreq_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RecReq_PROG, RecReq_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy1_PROG, Dummy1_VERS, dummy1_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (Dummy1_PROG, Dummy1_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy2_PROG, Dummy2_VERS, dummy2_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (Dummy2_PROG, Dummy2_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, Dummy3_PROG, Dummy3_VERS, dummy3_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (Dummy3_PROG, Dummy3_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
