/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "DSM.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 500, 0 };

int *
initializeserver_1(initializationNode *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, InitializeServer,
		(xdrproc_t) xdr_initializationNode, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char *
getmemptr_1(localNode *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetMemPtr,
		(xdrproc_t) xdr_localNode, (caddr_t) argp,
		(xdrproc_t) xdr_char, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

localNode *
getlocaldata_1(localNode *argp, CLIENT *clnt)
{
	static localNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetLocalData,
		(xdrproc_t) xdr_localNode, (caddr_t) argp,
		(xdrproc_t) xdr_localNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
recrep_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RecRep,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
getadd_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetAdd,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
sendadd_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SendAdd,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
getupdates_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetUpdates,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
sendupdates_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SendUpdates,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

localNode *
reqcs_1(localNode *argp, CLIENT *clnt)
{
	static localNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ReqCS,
		(xdrproc_t) xdr_localNode, (caddr_t) argp,
		(xdrproc_t) xdr_localNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

localNode *
reqcs1_1(localNode *argp, CLIENT *clnt)
{
	static localNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ReqCS1,
		(xdrproc_t) xdr_localNode, (caddr_t) argp,
		(xdrproc_t) xdr_localNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
recreq_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RecReq,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

localNode *
dummy1_1(localNode *argp, CLIENT *clnt)
{
	static localNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Dummy1,
		(xdrproc_t) xdr_localNode, (caddr_t) argp,
		(xdrproc_t) xdr_localNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char *
dummy2_1(ReqNode *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Dummy2,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_char, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReqNode *
dummy3_1(ReqNode *argp, CLIENT *clnt)
{
	static ReqNode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Dummy3,
		(xdrproc_t) xdr_ReqNode, (caddr_t) argp,
		(xdrproc_t) xdr_ReqNode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
